module.exports = {
  openapi: '3.0.0',
  info: { title: 'EventPulse API', version: '1.0.0', description: 'Event management backend API' },
  servers: [{ url: 'https://30907271803796-event-plus-8ohlnwdj4-event-plus.vercel.app', description: 'Production' }, { url: 'http://localhost:3000', description: 'Local development' }],
  paths: {
    '/health': { get: { responses: { 200: { description: 'Service health' } } } },
    '/api/auth/register': { post: { requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/Register' } } } }, responses: { 201: { description: 'Registered' }, 422: { description: 'Validation error' } } } },
    '/api/auth/login': { post: { requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/Login' } } } }, responses: { 200: { description: 'Authenticated' }, 401: { description: 'Invalid credentials' } } } },
    '/api/events': { get: { parameters: [{ name: 'category', in: 'query', schema: { type: 'string' } }, { name: 'city', in: 'query', schema: { type: 'string' } }, { name: 'startDate', in: 'query', schema: { type: 'string', format: 'date' } }, { name: 'endDate', in: 'query', schema: { type: 'string', format: 'date' } }, { name: 'search', in: 'query', schema: { type: 'string' } }, { name: 'page', in: 'query', schema: { type: 'integer', minimum: 1 } }, { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1 } }, { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['date', 'registrations'] } }, { name: 'order', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'] } }], responses: { 200: { description: 'Event list with pagination metadata' }, 400: { description: 'Invalid category id' } } }, post: { security: [{ bearerAuth: [] }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/EventInput' } } } }, responses: { 201: { description: 'Created' }, 401: { description: 'Authentication required' }, 403: { description: 'Admin required' }, 422: { description: 'Validation error' } } } },
    '/api/events/{id}': { get: { parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'Event details with category and organizer' }, 400: { description: 'Invalid event id' }, 404: { description: 'Event not found' } } }, patch: { security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/EventInput' } } } }, responses: { 200: { description: 'Updated' }, 401: { description: 'Authentication required' }, 403: { description: 'Admin required' }, 422: { description: 'Validation error' } } }, delete: { security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 204: { description: 'Deleted' }, 401: { description: 'Authentication required' }, 403: { description: 'Admin required' } } } }
  },
  components: { securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } }, schemas: { Register: { type: 'object', required: ['name', 'email', 'password'], properties: { name: { type: 'string' }, email: { type: 'string', format: 'email' }, password: { type: 'string', minLength: 6 } } }, Login: { type: 'object', required: ['email', 'password'], properties: { email: { type: 'string', format: 'email' }, password: { type: 'string' } } }, EventInput: { type: 'object', required: ['title', 'description', 'category', 'date', 'city', 'venue', 'capacity'], properties: { title: { type: 'string' }, description: { type: 'string' }, category: { type: 'string' }, date: { type: 'string', format: 'date-time' }, city: { type: 'string' }, venue: { type: 'string' }, capacity: { type: 'integer', minimum: 1 } } } } }
};
